// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEcBdzMdtx7ngwqOySrU1xrET7rPjvCrM',
    appId: '1:660882103875:web:b2eddbe4ca8760f5d1bef6',
    messagingSenderId: '660882103875',
    projectId: 'adamgriup-3b108',
    authDomain: 'adamgriup-3b108.firebaseapp.com',
    storageBucket: 'adamgriup-3b108.firebasestorage.app',
    measurementId: 'G-8RWKRX58XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-D6wSWEG85ixSPdneTeaSJ01lsZxwVPg',
    appId: '1:660882103875:android:dbff264e3bea6e80d1bef6',
    messagingSenderId: '660882103875',
    projectId: 'adamgriup-3b108',
    storageBucket: 'adamgriup-3b108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAVdhWt-6azTfrRv6MdkP-YQYXd7tZlhI',
    appId: '1:660882103875:ios:c748c7d27d514b94d1bef6',
    messagingSenderId: '660882103875',
    projectId: 'adamgriup-3b108',
    storageBucket: 'adamgriup-3b108.firebasestorage.app',
    iosBundleId: 'com.example.adamGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAVdhWt-6azTfrRv6MdkP-YQYXd7tZlhI',
    appId: '1:660882103875:ios:c748c7d27d514b94d1bef6',
    messagingSenderId: '660882103875',
    projectId: 'adamgriup-3b108',
    storageBucket: 'adamgriup-3b108.firebasestorage.app',
    iosBundleId: 'com.example.adamGroup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEcBdzMdtx7ngwqOySrU1xrET7rPjvCrM',
    appId: '1:660882103875:web:7d1d191dd7f508ecd1bef6',
    messagingSenderId: '660882103875',
    projectId: 'adamgriup-3b108',
    authDomain: 'adamgriup-3b108.firebaseapp.com',
    storageBucket: 'adamgriup-3b108.firebasestorage.app',
    measurementId: 'G-0M8L48CL9N',
  );
}
